import { CANVAS_DESIGN_WIDTH, type CanvasFrame } from "./types";

/** Hand-built proof-of-concept frame for Phase 7a — recreates the Editorial
 * Split hero look as canvas elements, to verify the renderer + scale-to-fit
 * approach end-to-end before any editor UI exists. Not shown to real users. */
export const seedHeroFrame: CanvasFrame = {
  id: "seed-hero",
  name: "Hero",
  width: CANVAS_DESIGN_WIDTH,
  height: 800,
  background: { color: "#3C0F1A" },
  elements: [
    {
      id: "big-letter",
      type: "text",
      x: 140,
      y: 140,
      width: 200,
      height: 160,
      rotation: 0,
      zIndex: 1,
      text: "A",
      fontFamily: "Playfair Display",
      fontSize: 130,
      fontWeight: 300,
      color: "#CBA25B",
      textAlign: "left",
      lineHeight: 1,
      letterSpacing: 0,
    },
    {
      id: "names",
      type: "text",
      x: 100,
      y: 360,
      width: 550,
      height: 90,
      rotation: 0,
      zIndex: 1,
      text: "Anna & Igor",
      fontFamily: "Playfair Display",
      fontSize: 56,
      fontWeight: 300,
      color: "#F2E4D8",
      textAlign: "left",
      lineHeight: 1.1,
      letterSpacing: 1,
    },
    {
      id: "date",
      type: "text",
      x: 100,
      y: 450,
      width: 400,
      height: 30,
      rotation: 0,
      zIndex: 1,
      text: "2026-09-12",
      fontFamily: "Inter",
      fontSize: 15,
      fontWeight: 400,
      color: "#F2E4D8",
      textAlign: "left",
      lineHeight: 1,
      letterSpacing: 3,
    },
    {
      id: "photo",
      type: "image",
      x: 680,
      y: 100,
      width: 420,
      height: 600,
      rotation: 0,
      zIndex: 1,
      imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
      objectFit: "cover",
      borderRadius: 4,
      filter: "grayscale(1) contrast(1.05)",
    },
  ],
};
